/* Generated By:JavaCC: Do not edit this line. AnalisadorLexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalisadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN = 5;
  /** RegularExpression Id. */
  int INTEGER = 6;
  /** RegularExpression Id. */
  int FLOAT = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int THEN = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int TO = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int DELIMITADOR_ESQ = 16;
  /** RegularExpression Id. */
  int DELIMITADOR_DIR = 17;
  /** RegularExpression Id. */
  int SUM = 18;
  /** RegularExpression Id. */
  int SUBTRACTION = 19;
  /** RegularExpression Id. */
  int MULTIPLICATION = 20;
  /** RegularExpression Id. */
  int DIVISION = 21;
  /** RegularExpression Id. */
  int ATRIBUICAO = 22;
  /** RegularExpression Id. */
  int BIGGER = 23;
  /** RegularExpression Id. */
  int MINOR = 24;
  /** RegularExpression Id. */
  int MINOR_EQUAL = 25;
  /** RegularExpression Id. */
  int BIGGER_EQUAL = 26;
  /** RegularExpression Id. */
  int DIFERENTE = 27;
  /** RegularExpression Id. */
  int EQUAL = 28;
  /** RegularExpression Id. */
  int ID = 29;
  /** RegularExpression Id. */
  int DELIMITAR_STRING = 30;
  /** RegularExpression Id. */
  int PONTO_VIRG = 31;
  /** RegularExpression Id. */
  int VIRGULA = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"ini\"",
    "\"int\"",
    "\"flu\"",
    "\"str\"",
    "\"se\"",
    "\"entao\"",
    "\"senao\"",
    "\"de\"",
    "\"ate\"",
    "<NUMBER>",
    "<DIGIT>",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<-\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"=\"",
    "<ID>",
    "\"\\\'\"",
    "\";\"",
    "\",\"",
  };

}
